version: '3.7'

services:
  yona:
    build: .
    image: pokev25/yona:1.14.0
    restart: always
    depends_on:
      - mariadb
    links:
      - mariadb
    environment:
      TZ: Asia/Seoul
      LANG: ko_KR.UTF-8
      BEFORE_SCRIPT: before.sh
      JAVA_OPTS: -Xmx2048m -Xms1024m
    ports:
      - "9000:9000"
    volumes:
      - ./yona/conf:/yona/data/conf
      - ./yona/logs:/yona/data/logs

  mariadb:
    image: mariadb:10.5.9
    restart: always
    environment:
      TZ: Asia/Seoul
      LANG: ko_KR.UTF-8
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yona
      MYSQL_USER: yona
      MYSQL_PASSWORD: password
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports: 
      - 3306:3306 
    volumes: 
      - ./mysql/data:/var/lib/mysql
      - ./mysql/etc/conf.d:/etc/mysql/conf.d
      - ./mysql/etc/mariadb.conf.d:/etc/mysql/mariadb.conf.d

  adminer:
    image: adminer:4.8.0-standalone
    restart: always
    depends_on:
      - mariadb
    environment:
      TZ: Asia/Seoul
      LANG: ko_KR.UTF-8
    links:
      - mariadb
    ports:
      - 8080:8080
